version: "3.7"
services: 
  db:
    image: postgres
    networks: 
      - webnet
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: slom
  web: 
    image: slom-server
    ports: 
      - "8081:8081"
    networks: 
      - webnet
    environment: 
      DB_HOST: db
networks: 
  webnet:
